### ISSUE TITLE
padronizador para complemento

### ISSUE THREAD

**Issue by lucasmation** [ipeaGIT/enderecopadrao#1]
Um aspecto importante é padronizar os complementos. 
Por exmeplko CASA CS, APTP ap AP, etc.... harmonizar espaços, etc.

**Comment by lucasmation** [comment]
@dhersz, por favor foca neste issue

**Comment by dhersz** [comment]
Não tenho acesso a nenhuma base com um campo de complemento a parte por enquanto. O Rafa já solicitou meu acesso às bases de CPF e CNPJ, mas ainda não o concederam.

Você sabe me indicar alguma base não restrita que tenho esse campo? Não sei também se seria possível compartilhar uma amostra de valores de complemento pra alguma das bases que você esteja usando. Imagino que não teria grandes problemas quanto à privacidade da informação, já que é só o complemento, mas não sei se isso é permitido.

**Comment by lucasmation** [comment]
Voce nao está usando CadUnico? TSEE?

acho que podemos sim, vou tentar salvar em:
\\storage6\usuarios\CGDTI\IpeaDataLab\projetos\enderecos
me diz se voce tem acesso para ler/escrever nesta pasta.

**Comment by dhersz** [comment]
Tenho acesso à pasta sim.

**Comment by dhersz** [comment]
Primeira versão nesse commit https://github.com/ipeaGIT/enderecopadrao/commit/a6db4f3332d3a9c1f6384bed687a8d1f18976415.

Ainda tem muito a avançar, vou deixar aberto até ter uma versão um pouquinho melhor no ar.
