### ISSUE TITLE
detecção de valores non-sense no logradouro e afins pegando coisas demais

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/enderecopadrao#11]
e.g. logradouro = "11" quando padronizado vira NA porque a atual detecção no logradouro considera qualquer valor que começa com um caracter e só ele existe repetido até o fim como non-sense

ou seja, 22, 33, 44, 55, 111, tudo é flagado como non-sense

provavelmente melhor pensar:

- qualquer caracter não numérico repetido do começo ao fim é non-sense - e.g. aa, aaa, bb, ---, xxx, etc. (**EXCEÇÃO:** números romanos - II, III)
- se for numérico, considerar um número de repetições razoável. existem casos de RUA 11, RUA 1, etc, mas dificilmente existe RUA 999, RUA 111. provavelmente qualquer coisa que se repita 3+ vezes é non-sense

**Comment by dhersz** [comment]
também tá pegando coisa de menos.

essa aqui no campo de bairro: "X. X. X. X. X. X. X. X. X. X. X. X. X. X."

**Comment by rafapereirabr** [comment]
acho que o caso " X. X. X. X." deve ser bem raro, nao? Vale a pena incluir?

**Comment by dhersz** [comment]
Vai na mesma linha das grafias, que a gente tava falando outro dia.
