### ISSUE TITLE
Lidar com algarismo romano

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/enderecopadrao#18]
sao muitos casos?

> nRomanos = {"I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX", "XXI", "XXII", "XXIII", "XXIV", "XXV", "XXVI", "XXVII", "XXVIII", "XXIX", "XXX", "XXXI", "XXXII", "XXXIII", "XXXIV", "XXXV", "XXXVI", "XXXVII", "XXXVIII", "XXXIX", "XL",  "XLI", "XLII", "XLIII", "XLIV", "XLV", "XLVI", "XLVII", "XLVIII", "XLIX" };

**Comment by dhersz** [comment]
Eu voto por deixar em romano mesmo.

**Comment by rafapereirabr** [comment]
sim, tmb acho que algarismo romano deveria ficar em romano. Nao lembro agora qual caso eu tinha em mente quando coloquei isso aqui rsrsr . Acho que podemos fechar
