### ISSUE TITLE
numeros por extenso

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/enderecopadrao#20]
> nExtenso = { "UM", "HUM", "PRIMEIRO", "SEGUNDO", "DOIS", "DUAS", "TRES", "TREZ", "QUATRO", "CINCO", "SEIS", "SETE", "OITO", "NOVE", "DEZ", "ONZE", "DOZE", "TREZE", "TRESE", "QUATORZE", "CATORZE", "QUINZE", "DEZESSEIS", "DEZESSETE", "DEZOITO", "DEZENOVE", "VINTE", "TRINTA", "QUARENTA", "CINQUENTA", "SESSENTA", "SETENTA", "OITENTA", "NOVENTA", "CEM", "CENTO", "DUZENTOS", "TREZENTOS", "TRESENTOS", "QUATROCENTOS", "QUINHENTOS", "SEISCENTOS", "SETECENTOS", "OITOCENTOS", "NOVECENTOS", "MIL" }

> nInteiro = {1,1,1,2,2,2,3,3,4,5,6,7,8,9,10,11,12,13,13,14,14,15,16,17,18,19,20,30,40,50,60,7 0,80,90, 100,100,200,300,300,400,500,600,700,800,900,1000};

**Comment by dhersz** [comment]
não é tão simples assim. tem vários casos que são tipo "BR CENTO E DEZESSEIS". se for usar essa lista aík por exemplo, ficaria "BR CENTO E 16". transformar extenso->numérico ou vice-versa é um trabalho muito complicado, não sei se vale a pena.
