### ISSUE TITLE
manter no output uma coluna com o abbrev_state

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/enderecopadrao#22]

**Comment by dhersz** [comment]
Pelo que entendi, a ideia seria manter as colunas não padronizadas no output, certo? Modifiquei a função `padronizar_enderecos()` pra manter as colunas originais e criar colunas com nome `<nome_original>_padr` pra botar os valores padronizados. É isso?

**Comment by rafapereirabr** [comment]
Sim e nao. Sim para manter as colunas originais e criar colunas com nome `<nome_original>_padr`. Meu ponto é que é possivel que o input do usuario nao tenha a sigla do estado, então seria importante gerar tambem. Isso falicitaria a integração com o {geocodebr}
