### ISSUE TITLE
Nome de municipio como input

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/enderecopadrao#23]
O comportamento usual é que os dados de input tem o nome do municipio, e nao necessariamente o codigo. Então talvez fosse o caso de pensarmos dividir a funcao `padronizar_municipios()` em: 
- `padronizar_municipios_codigos()`
- `padronizar_municipios_nomes()`

ou algo como: `padronizar_municipios(...., tipo = c("codigo", "nome"))`

**Comment by dhersz** [comment]
O que fazer com municípios com nomes iguais?

**Comment by rafapereirabr** [comment]
O pacote só padroniza o nome. Acho que nao precisa se preocupar se existem municipios homoninos. Até porque o input da funcao tambem lida com a UF (e só podem existir municipios homonimos em UFs distintas).

Essa minha sugestão é porque as pessoas nunca usam 'codigo de municipio' como input para fazer geocode neh.

**Comment by dhersz** [comment]
Eu não entendi o que você quis dizer, então. Se for que a função deve receber código e retornar o nome, ela já faz isso. Achei que você quisesse uma função que dava o nome e retornava o código.

**Comment by rafapereirabr** [comment]
Minha ideia era isso aqui, colocar todo texto em caixa alta e sem characteres especiais, que é o que o pacote faz para outros campos também. 
```
padronizar_municipios_nomes("São Paulo")
> SAO PAULO
````

**Comment by dhersz** [comment]
Mas ele já faz isso hehe

**Comment by dhersz** [comment]
Ele aceita tanto o nome do município quanto o código.

**Comment by rafapereirabr** [comment]
foi mal. Eu tinha feito algum teste q tinha dado erro e achei que fosse isso. Confusao minha entao.
