### ISSUE TITLE
Padronizar os nomes das colunas padronizadas em caixa baixa

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/enderecopadrao#27]
Na versao atual do codigo, o pacote mantem o nome das colunas originais e somente adiciona o sufixo `"_padr"`. 

https://github.com/ipeaGIT/enderecopadrao/blob/2e91614368f1f08357f80ceaf619910216bb606d/R/padronizar_enderecos.R#L61

Não seria uma melhor que os nomes das colunas de output sejam sempre os mesmos, como estava antes? tipo:

- logradouto_padr
- numero_padr
- bairro_padr
- cep_padr
- municipio_padr
- estado_padr

```
library(enderecopadrao)
library(geocodebr)

# open input data
data_path <- system.file("extdata/sample_1.csv", package = "geocodebr")
input_df <- read.csv(data_path)


input_table = input_df
logradouro = "nm_logradouro"
numero = "Numero"
complemento = "Complemento"
cep = "Cep"
bairro = "Bairro"
municipio = "nm_municipio"
estado = "nm_uf"
output_simple = FALSE
ncores = NULL
showProgress = TRUE


# correspondence of column names
campos <- enderecopadrao::correspondencia_campos(
  logradouro = {logradouro},
  numero = {numero},
  complemento = {complemento},
  cep = {cep},
  bairro = {bairro},
  municipio = {municipio},
  estado = {estado}
)

# padroniza input do usuario
input_padrao <- enderecopadrao::padronizar_enderecos(
  enderecos = input_table,
  campos_do_endereco = campos
)

names(input_df)
```
> [1] "ID"            "nm_logradouro" "Numero"        "Complemento"   "Cep"           "Bairro"       
[7] "nm_municipio"  "code_muni"     "nm_uf" 

```
names(input_padrao)
```
>  [1] "ID"                 "code_muni"          "nm_logradouro"      "Numero"            
 [5] "Complemento"        "Cep"                "Bairro"             "nm_municipio"      
 [9] "nm_uf"              "nm_logradouro_padr" "Numero_padr"        "Complemento_padr"  
[13] "Cep_padr"           "Bairro_padr"        "nm_municipio_padr"  "nm_uf_padr"

**Comment by dhersz** [comment]
e se já tiver uma coluna "logradouro_padr" antes, por exemplo? sobrescreve?

**Comment by rafapereirabr** [comment]
a chance de ja ter outra coluna com mesmo nome é baixa neh. Mas acho q nesse caso o ideal seriar gerar um erro

**Comment by dhersz** [comment]
Ajustado em https://github.com/ipeaGIT/enderecopadrao/commit/8d5e47db213432742a7c03cbc628e51034478d43.

Exemplo:

``` r
library(enderecopadrao)

ends <- data.frame(
  Log = "r ns sra da piedade",
  Num = 20,
  Est = 23
)

padronizar_enderecos(
  ends,
  correspondencia_campos(logradouro = "Log", numero = "Num", estado = "Est")
)
#>                    Log   Num   Est              logradouro_padr numero_padr
#>                 <char> <num> <num>                       <char>      <char>
#> 1: r ns sra da piedade    20    23 RUA NOSSA SENHORA DA PIEDADE          20
#>    estado_padr
#>         <char>
#> 1:       CEARA
```

Se já tiver uma coluna com esse nome ele dá um warning:

```r
ends <- data.frame(
  logradouro_padr = "r ns sra da piedade",
  numero_padr = 20,
  estado_padr = 23
)

padronizar_enderecos(
  ends,
  correspondencia_campos(
    logradouro = "logradouro_padr",
    numero = "numero_padr",
    estado = "estado_padr"
  )
)
#> Warning in padronizar_enderecos(ends, correspondencia_campos(logradouro = "logradouro_padr", : As seguintes colunas foram encontradas no input e serão sobrescritas no output:
#> `logradouro_padr`, `numero_padr` e `estado_padr`.
#>                 logradouro_padr numero_padr estado_padr
#>                          <char>      <char>      <char>
#> 1: RUA NOSSA SENHORA DA PIEDADE          20       CEARA
```
