### ISSUE TITLE
detectar valores non-sense (especialmente em logradouros)

### ISSUE THREAD

**Issue by lucasmation** [ipeaGIT/enderecopadrao#5]
ALém de uma string vazia, "", vi casos como:
- '***'  Um ou mais vezes um carcter estanho repitido
- 'AAAA' Um ou mais vezes uma letra repetida. 
Parecem ser casos em que o usuário digita qq coisa para burlar o filtro 
O que fazer nestes casos?

Acho que tem que transformar em NA.... (e tb os vazios). 
@dhersz, o que acha?

**Comment by dhersz** [comment]
Nunca tinha notado esses casos. Em que base você tá encontrando esses valores? Queria dar uma olhada em como os outros campos são preenchidos quando isso acontece.

Transformar em NA pode ser uma boa.

Na verdade, hoje o pacote transforma NAs em strings vazias (""). Fiz isso no começo pensando que valores NA poderiam resultar em problemas quando usasse os endereços pro geocode, mas na verdade nunca testei esse comportamento (se gera problemas ou não). Vou testar isso. "Conceitualmente", concordo que transformar valores inválidos em NA faz mais sentido.

**Comment by lucasmation** [comment]
Na base do CPF, na do CadUnico, na TSEE. Acontece muito tb com nomes de pessoas especialmente nome da mae e do pai nos cadastros. 

Acho que, conceitualmente, a ausência de informação tem que ser classificada como tal, isso é, como NA. A função de geocode deveria saber lidar com isso e nem rodar, ou rodar sem aquela variável. 

Dito isso, como tenho salvo/lido usando o fread/fwrite, e ele mantem os vazions como "", as vezes eu esqueço de fazer esta limpeza.

**Comment by dhersz** [comment]
Rascunho em https://github.com/ipeaGIT/enderecopadrao/commit/2a3aae0fab47c0bb2e7377f2f336ecdccba5fb36. Por enquanto usando "" em vez de NA porque preciso fazer uns testes com NA. Mas nos próximos dias já vou mudar isso.

**Comment by dhersz** [comment]
Conversão de vazios/non-sense em NA feita em https://github.com/ipeaGIT/enderecopadrao/commit/2f54e0a18edf6c78ab26e7abcd1101dbaad2c6e2.
